# Generated by Django 5.2.3 on 2025-06-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
