# Generated by Django 5.2.3 on 2025-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net_content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
